In [160]:
import pandas as pd
import numpy as np
import seaborn as sns

In [161]:
com_df = pd.read_csv('combined_SF_smaple_data.csv')

In [162]:
com_df.shape

(912423, 68)

In [163]:
com_df.head()

,fico,dt_first_pi,flag_fthb,dt_matr,cd_msa,mi_pct,cnt_units,occpy_sts,cltv,dti,...,defaulted_upb,prepaid_upb,GT_90_days_delinquecy,default,prepayment,lpi2zero,delinquent_interest,net_loss,loss_severity,total_proceeds
0,799.0,1999-03-01,N,2029-01-01,37620.0,0.0,1.0,P,70.0,25.0,...,0.0,41869.88,0,0,1,0,0.0,0.0,0.0,0.0
1,635.0,2002-12-01,N,2029-04-01,10420.0,0.0,1.0,P,76.0,21.0,...,0.0,82069.46,0,0,1,0,0.0,0.0,0.0,0.0
2,787.0,1999-05-01,N,2029-04-01,12060.0,999.0,1.0,P,80.0,18.0,...,0.0,120122.19,0,0,1,0,0.0,0.0,0.0,0.0
3,726.0,1999-04-01,N,2029-03-01,28140.0,0.0,1.0,P,80.0,37.0,...,0.0,104737.29,0,0,1,0,0.0,0.0,0.0,0.0
4,748.0,1999-05-01,X,2029-04-01,17140.0,999.0,1.0,P,80.0,28.0,...,0.0,111879.89,0,0,1,0,0.0,0.0,0.0,0.0

In [164]:
com_df.columns

Index(['fico', 'dt_first_pi', 'flag_fthb', 'dt_matr', 'cd_msa', 'mi_pct',
       'cnt_units', 'occpy_sts', 'cltv', 'dti', 'orig_upb', 'ltv', 'int_rt',
       'channel', 'ppmt_pnlty', 'prod_type', 'st', 'prop_type', 'zipcode',
       'id_loan', 'loan_purpose', 'orig_loan_term', 'cnt_borr', 'seller_name',
       'servicer_name', 'flag_sc', 'fico_bins', 'cltv_bins', 'dti_bins',
       'ltv_bins', 'mi_pct_bins', 'Year', 'svcg_cycle', 'current_upb',
       'delq_sts', 'loan_age', 'mths_remng', 'repch_flag', 'flag_mod',
       'cd_zero_bal', 'dt_zero_bal', 'current_int_rt', 'non_int_brng_upb',
       'dt_lst_pi', 'mi_recoveries', 'net_sale_proceeds', 'non_mi_recoveries',
       'expenses', 'legal_costs', 'maint_pres_costs', 'taxes_ins_costs',
       'misc_costs', 'actual_loss', 'modcost', 'stepmod_ind',
       'delq_sts_180_date', 'last_payment_date', 'delq_sts_180_upb',
       'defaulted_upb', 'prepaid_upb', 'GT_90_days_delinquecy', 'default',
       'prepayment', 'lpi2zero', 'delinquent_interest', 'net_loss',
       'loss_severity', 'total_proceeds'],
      dtype='object')

In [165]:
def orig_summary_statistics(x):
    names = {
        'loan_count': x['id_loan'].count(),
        'total_orig_UPB ($B)':  x['orig_upb'].sum()/1000000000,
        'average_orig_UPB':  x['orig_upb'].mean(),
        'weighted_average_fico':  (x.loc[x.fico!=9999,'orig_upb'] * x.loc[x.fico!=9999,'fico']).sum()/x.loc[x.fico!=9999,'orig_upb'].sum(),
        'weighted_average_cltv':  (x.loc[x.cltv!=999,'orig_upb'] * x.loc[x.cltv!=999,'cltv']).sum()/x.loc[x.cltv!=999,'orig_upb'].sum(),
        'weighted_average_ltv':  (x.loc[x.ltv!=999,'orig_upb'] * x.loc[x.ltv!=999,'ltv']).sum()/x.loc[x.ltv!=999,'orig_upb'].sum(),
        'weighted_average_dti':  (x.loc[x.dti!=999,'orig_upb'] * x.loc[x.dti!=999,'dti']).sum()/x.loc[x.dti!=999,'orig_upb'].sum(),
        }

    return pd.Series(names, index=['loan_count', 'total_orig_UPB ($B)', 'average_orig_UPB',
                                   'weighted_average_fico', 'weighted_average_cltv', 'weighted_average_ltv','weighted_average_dti'])

In [166]:
orig_summary_statistic = com_df.groupby("Year").apply(orig_summary_statistics).round(1)

In [67]:
# orig_summary_statistic.to_csv("sample_SF_summary_Statistics.csv",index=False)

In [167]:
orig_summary_statistic

,loan_count,total_orig_UPB ($B),average_orig_UPB,weighted_average_fico,weighted_average_cltv,weighted_average_ltv,weighted_average_dti
Year,,,,,,,
1999,50000.0,6.3,125690.1,711.3,78.0,77.9,33.6
2000,50000.0,6.5,130918.9,712.2,79.0,78.4,35.2
2001,49999.0,7.4,148131.9,714.7,76.5,75.7,33.8
2002,49997.0,7.7,154680.4,716.6,75.0,74.0,34.1
2003,49997.0,8.0,160694.7,723.5,73.8,72.4,33.1
2004,49997.0,8.3,166464.2,718.3,75.4,73.6,35.8
2005,49999.0,8.5,170689.3,724.4,72.1,70.3,36.3
2006,49997.0,9.0,179596.6,723.9,74.3,71.8,37.6
2007,49996.0,9.2,183760.9,724.8,75.8,73.1,37.8
2008,49994.0,10.2,203975.4,743.0,72.7,70.9,37.0
2009,49999.0,10.7,213726.0,762.8,67.9,66.1,32.5
2010,49998.0,10.4,208390.8,763.3,68.7,67.2,32.4
2011,49997.0,10.9,217078.6,764.3,69.5,68.1,32.4
2012,49997.0,11.1,222675.4,767.0,69.9,68.5,31.4
2013,50000.0,10.9,217599.7,758.7,73.1,72.0,32.9
2014,50000.0,11.0,219868.1,751.9,76.7,76.0,34.3
2015,49999.0,11.5,229370.5,752.4,75.1,74.4,34.4
2016,50000.0,12.0,239712.9,751.3,74.3,73.7,34.7
2017,12457.0,2.9,230705.0,746.4,74.8,74.2,35.8

In [176]:
def performance_summary_statistics(x):
    names = {
        'loan_count': x['id_loan'].count(),
        'prepay_loan(%)':  x.loc[x.cd_zero_bal.isin(['P','R']),'id_loan'].count()*100/x['id_loan'].count(),
        'default_loan(%)' :  x.loc[x.default==1,'id_loan'].count()*100/x['id_loan'].count(),
        'active_loan(%)':  x.loc[x.cd_zero_bal=='C','id_loan'].count()*100/x['id_loan'].count(),
        'cumulative_post‐default_event_repurchase(%)':  x.loc[(x.cd_zero_bal.isin(['S','F']))&(x.repch_flag=='Y'),'id_loan'].count()*100/x['id_loan'].count(),
        'ever_D180(%)':  x.loc[(x.delq_sts_180_upb!=0)|(x.delq_sts=='R'),'id_loan'].count()*100/x['id_loan'].count(),
        'D180_and_pre‐D180_credit_event(%)':  x.loc[(x.delq_sts_180_upb!=0)|(x.delq_sts=='R')|(x.default==1),'id_loan'].count()*100/x['id_loan'].count(),
        'cumulative_modification(%)' : x.loc[x.flag_mod=='Y','id_loan'].count()*100/x['id_loan'].count(),
        'actuall_loss($M)':  -x.actual_loss.sum()/1000000,
        'total_orig_UPB($B)':  x.orig_upb.sum()/1000000000,
        'prepaid_upb(%)':  x.prepaid_upb.sum()*100/x.orig_upb.sum(),
        'defaulted_upb(%)': x.defaulted_upb.sum()*100/x.orig_upb.sum(),
        'current_upb(%)':  x.current_upb.sum()*100/x.orig_upb.sum(),
        'post-defaulted_upb(%)':  x.loc[(com_df.default==1)&(x.repch_flag=='Y'),'defaulted_upb'].sum()*100/x.orig_upb.sum(),
        'original_UPB_ever_D180(%)':  (x.delq_sts_180_upb.sum()+x.loc[(x.cd_zero_bal=='F'),'defaulted_upb'].sum()+x.loc[(x.delq_sts=='R')&(x.delq_sts_180_upb==0),'current_upb'].sum())*100/x.orig_upb.sum(),
        'original_UPB_D180_and_pre_D180_credit_event(%)':  (x.delq_sts_180_upb.sum()+x.loc[(x.default==1),'defaulted_upb'].sum()+x.loc[(x.delq_sts=='R')&(x.delq_sts_180_upb==0),'current_upb'].sum())*100/x.orig_upb.sum(),
        'UPB_weighted_cumulative_modification(%)':  x.loc[x.flag_mod=='Y','current_upb'].sum()*100/x.orig_upb.sum()
    }

    return pd.Series(names, index=['loan_count', 'prepay_loan(%)', 'default_loan(%)',
                                   'active_loan(%)', 'cumulative_post‐default_event_repurchase(%)', 'ever_D180(%)'
                                   ,'D180_and_pre‐D180_credit_event(%)','actuall_loss($M)','total_orig_UPB($B)',
                                  'prepaid_upb(%)','defaulted_upb(%)','current_upb(%)','post-defaulted_upb(%)','original_UPB_ever_D180(%)'
                                  ,'original_UPB_D180_and_pre_D180_credit_event(%)','UPB_weighted_cumulative_modification(%)'])

In [177]:
performance_summary_statistic = com_df.groupby("Year").apply(performance_summary_statistics).round(1)

In [179]:
performance_summary_statistic.to_csv("sample_SF_performance_summary_Statistics.csv",index=False)

In [178]:
performance_summary_statistic

,loan_count,prepay_loan(%),default_loan(%),active_loan(%),cumulative_post‐default_event_repurchase(%),ever_D180(%),D180_and_pre‐D180_credit_event(%),actuall_loss($M),total_orig_UPB($B),prepaid_upb(%),defaulted_upb(%),current_upb(%),post-defaulted_upb(%),original_UPB_ever_D180(%),original_UPB_D180_and_pre_D180_credit_event(%),UPB_weighted_cumulative_modification(%)
Year,,,,,,,,,,,,,,,,
1999,50000.0,96.9,1.4,1.7,0.2,2.3,2.4,11.2,6.3,91.9,1.0,0.7,0.1,2.3,2.6,NaN
2000,50000.0,97.5,1.5,1.0,0.2,2.2,2.3,14.1,6.5,95.3,1.1,0.4,0.2,2.4,2.6,0.0
2001,49999.0,96.2,1.6,2.1,0.2,2.4,2.5,21.4,7.4,93.5,1.1,0.9,0.2,2.3,2.5,0.0
2002,49997.0,94.3,1.9,3.8,0.2,3.0,3.1,31.3,7.7,91.0,1.3,1.8,0.1,2.8,3.1,0.0
2003,49997.0,89.2,2.4,8.4,0.1,3.9,4.0,50.0,8.0,81.5,1.8,4.6,0.1,4.0,4.6,0.0
2004,49997.0,86.2,3.7,10.1,0.2,5.8,6.0,96.5,8.3,79.2,3.1,6.0,0.2,6.6,7.8,0.0
2005,49999.0,83.0,5.4,11.6,0.2,7.7,8.2,203.9,8.5,72.8,5.3,6.6,0.2,10.0,12.6,0.0
2006,49997.0,81.9,8.2,9.8,0.4,11.1,11.8,361.3,9.0,75.5,8.3,6.4,0.4,15.1,19.2,0.0
2007,49996.0,79.7,8.9,11.4,0.8,12.6,13.4,374.6,9.2,74.9,9.0,7.7,0.8,17.2,21.5,0.0
2008,49994.0,85.6,4.2,10.2,0.3,6.9,7.2,163.8,10.2,82.2,4.0,6.2,0.4,8.6,10.6,0.0
2009,49999.0,80.1,0.6,19.3,0.0,1.1,1.2,17.1,10.7,76.0,0.5,11.2,0.0,1.1,1.4,0.0
2010,49998.0,70.7,0.3,29.0,0.0,0.7,0.7,6.3,10.4,68.1,0.2,17.7,0.0,0.6,0.7,0.0
2011,49997.0,62.2,0.1,37.7,0.0,0.4,0.4,2.8,10.9,61.5,0.1,24.3,NaN,0.4,0.4,0.0
2012,49997.0,36.5,0.0,63.5,0.0,0.2,0.2,1.0,11.1,34.2,0.0,48.9,0.0,0.2,0.2,0.0
2013,50000.0,33.6,0.1,66.3,0.0,0.2,0.3,0.7,10.9,32.8,0.1,54.2,0.0,0.2,0.3,0.0
2014,50000.0,36.5,0.0,63.4,0.0,0.3,0.3,0.6,11.0,39.9,0.0,52.2,NaN,0.3,0.3,0.0
2015,49999.0,18.1,0.0,81.8,0.0,0.1,0.1,0.0,11.5,19.6,0.0,74.1,NaN,NaN,NaN,0.0
2016,50000.0,6.6,0.0,93.4,0.0,0.0,0.0,-0.0,12.0,6.7,0.0,89.7,NaN,NaN,NaN,0.0
2017,12457.0,2.6,0.0,97.4,0.0,0.0,0.0,-0.0,2.9,3.1,0.0,95.0,NaN,NaN,NaN,NaN

In [174]:
com_df.loc[com_df.delq_sts=='R','current_upb'].shape[0],com_df[(com_df.cd_zero_bal=='F')&(com_df.delq_sts_180_upb==0)].shape[0],com_df.loc[(com_df.delq_sts=='R')&(com_df.delq_sts_180_upb==0),'current_upb'].shape[0]

(12559, 1905, 1918)

In [173]:
(com_df.delq_sts_180_upb.sum()+com_df.loc[(com_df.default==1)&(com_df.delq_sts_180_upb==0),'defaulted_upb'].sum()+com_df.loc[(com_df.delq_sts=='R')&(com_df.delq_sts_180_upb==0),'current_upb'].sum())*100/com_df.orig_upb.sum()

3.0456262476063669

In [152]:
com_df.loc[com_df.flag_mod=='Y','current_upb'].sum()*100/com_df.orig_upb.sum()

0.007909494832202409

In [159]:
com_df.loc[(com_df.flag_mod=='Y')&(com_df.current_upb!=0)].shape[0]

80